_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 2
                - 3
            "2":
                - 1
                - 2
                - 3
                - 11
                - 49
            "3":
                - 13
                - 16
                - 55
            "4": 3.11.3
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
algorithm:
    value: A2C
ent_coef:
    value: 0.01
env:
    value: FrozenLake-v1
gamma:
    value: 0.99
learning_rate:
    value: 0.0007
max_grad_norm:
    value: 0.5
n_steps:
    value: 5
policy:
    value: MlpPolicy
vf_coef:
    value: 0.25
