_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 2
                - 3
            "2":
                - 1
                - 2
                - 3
                - 11
                - 49
            "3":
                - 2
                - 13
                - 16
                - 55
                - 61
            "4": 3.11.3
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
batch_size:
    value: 64
check_freq:
    value: 1000
clip_range:
    value: 0.2
ent_coef:
    value: 0.01
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
max_grad_norm:
    value: 0.5
n_steps:
    value: 5
policy:
    value: MlpPolicy
save_dir:
    value: ./frozenlake/frozenlake_ppo/models
steps:
    value: 100000
vf_coef:
    value: 0.5
